window.SIMATA_BACKUP_ENCRYPTED = [
  {
    "id": "1766660489023",
    "nama": "muhammad salam",
    "nik": "3509131209880006",
    "whatsapp": "085647709114",
    "profesi": "Nelayan Penuh Waktu",
    "status": "Pemilik Kapal",
    "tahunLahir": 1988,
    "usia": 37,
    "kecamatan": "Kendit",
    "desa": "Rajekwesi",
    "alatTangkap": "Pukat Tarik",
    "namaKapal": "cendhanu",
    "jenisKapal": "Perahu Insang",
    "jenisIkan": "Ikan Tongkol, Ikan Kembung, Ikan Selar, Ikan Tenggiri, Ikan Layang, Kakap Merah",
    "usahaSampingan": "minimarket",
    "tanggalValidasi": "2025-12-25",
    "validator": "cha",
    "driveLink": "",
    "kodeValidasi": "VLD-GQX0N2",
    "keterangan": ""
  },
  {
    "id": 1762425289023,
    "nama": "cinta",
    "nik": "3509131209880000",
    "whatsapp": "82324864999",
    "profesi": "Nelayan Penuh Waktu",
    "status": "Anak Buah Kapal",
    "tahunLahir": 1987,
    "usia": 38,
    "kecamatan": "panarukan",
    "desa": "kilensari",
    "alatTangkap": "Pukat Tarik",
    "namaKapal": "bunga",
    "jenisKapal": "Perahu Insang",
    "jenisIkan": "Ikan Tongkol, Ikan Kembung, Ikan Selar",
    "usahaSampingan": "ternak",
    "tanggalValidasi": 46015,
    "validator": "arya",
    "driveLink": "",
    "kodeValidasi": "VLD-GEC0N2",
    "keterangan": ""
  }
];
