// DATA NELAYAN GLOBAL - SISTEM PEMETAAN NELAYAN
// File: reload.js
// Dibuat: 12/1/2026, 09.43.38
// Jumlah Data: 16

window.SIMATA_BACKUP_DATA = [
  {
    "id": 1768024012170,
    "nama": "M. HOSEN MAKKI",
    "nik": "3512020603660001",
    "whatsapp": "082214641188",
    "profesi": "Nelayan Penuh Waktu",
    "status": "Anak Buah Kapal",
    "tahunLahir": "1966",
    "usia": "60",
    "kecamatan": "Besuki",
    "desa": "Blimbing",
    "alatTangkap": "Pancing Ulur",
    "namaKapal": "-",
    "jenisKapal": "-",
    "jenisIkan": "Ikan Marlin (Makaira spp.), Ikan Cucut (Carcharhinus limbatus)",
    "usahaSampingan": "",
    "tanggalValidasi": "2026-01-10",
    "validator": "MUHAMMAD S",
    "driveLink": "",
    "kodeValidasi": "VLD-1X39V8",
    "keterangan": ""
  },
  {
    "id": 1768024193373,
    "nama": "MOH. MISBAH",
    "nik": "3512021309830005",
    "whatsapp": "00000000",
    "profesi": "Nelayan Penuh Waktu",
    "status": "Anak Buah Kapal",
    "tahunLahir": "1983",
    "usia": "43",
    "kecamatan": "Besuki",
    "desa": "Bloro",
    "alatTangkap": "Pukat Cincin",
    "namaKapal": "-",
    "jenisKapal": "-",
    "jenisIkan": "Ikan Selar Kuning (Selaroides leptolepis), Ikan Layang (Decapterus spp.), Ikan Banyar (Carangoides spp.)",
    "usahaSampingan": "",
    "tanggalValidasi": "2026-01-10",
    "validator": "MUHAMMAD S",
    "driveLink": "",
    "kodeValidasi": "VLD-CL7Y77",
    "keterangan": ""
  },
  {
    "id": 1768024420072,
    "nama": "SUPATNO",
    "nik": "3512020304780005",
    "whatsapp": "00000000",
    "profesi": "Nelayan Penuh Waktu",
    "status": "Anak Buah Kapal",
    "tahunLahir": "1978",
    "usia": "48",
    "kecamatan": "Besuki",
    "desa": "Jetis",
    "alatTangkap": "Pancing",
    "namaKapal": "-",
    "jenisKapal": "-",
    "jenisIkan": "Ikan Tembang (Sardinella gibbosa), Ikan Japuh (Caranx spp.), Ikan Banyar Mata Besar (Megalaspis cordyla)",
    "usahaSampingan": "",
    "tanggalValidasi": "2026-01-10",
    "validator": "MUHAMMAD S",
    "driveLink": "",
    "kodeValidasi": "VLD-91U5I2",
    "keterangan": ""
  },
  {
    "id": 1768024524874,
    "nama": "MUTHAR",
    "nik": "3512020104810004",
    "whatsapp": "00000000",
    "profesi": "Nelayan Penuh Waktu",
    "status": "Anak Buah Kapal",
    "tahunLahir": "1981",
    "usia": "45",
    "kecamatan": "Besuki",
    "desa": "Jetis",
    "alatTangkap": "Pukat Cincin",
    "namaKapal": "-",
    "jenisKapal": "-",
    "jenisIkan": "Ikan Japuh (Caranx spp.), Ikan Lemuru (Sardinella lemuru), Ikan Banyar (Carangoides spp.), Ikan Banyar Mata Besar (Megalaspis cordyla)",
    "usahaSampingan": "",
    "tanggalValidasi": "2026-01-10",
    "validator": "MUHAMMAD S",
    "driveLink": "",
    "kodeValidasi": "VLD-VCR738",
    "keterangan": ""
  },
  {
    "id": 1768024693008,
    "nama": "HASAN BASRI",
    "nik": "3512022206820004",
    "whatsapp": "00000000",
    "profesi": "Nelayan Penuh Waktu",
    "status": "Anak Buah Kapal",
    "tahunLahir": "1982",
    "usia": "44",
    "kecamatan": "Besuki",
    "desa": "Kalimas",
    "alatTangkap": "Pukat Cincin",
    "namaKapal": "-",
    "jenisKapal": "-",
    "jenisIkan": "Ikan Cucut (Carcharhinus limbatus), Ikan Selar Kuning (Selaroides leptolepis), Ikan Layang (Decapterus spp.), Ikan Japuh (Caranx spp.), Ikan Lemuru (Sardinella lemuru), Ikan Banyar (Carangoides spp.)",
    "usahaSampingan": "",
    "tanggalValidasi": "2026-01-10",
    "validator": "MUHAMMAD S",
    "driveLink": "",
    "kodeValidasi": "VLD-3WEC4L",
    "keterangan": ""
  },
  {
    "id": 1768027674319,
    "nama": "AMRI WALIYADI",
    "nik": "3512132707870002",
    "whatsapp": "00000000",
    "profesi": "Nelayan Penuh Waktu",
    "status": "Anak Buah Kapal",
    "tahunLahir": "1987",
    "usia": "39",
    "kecamatan": "Asembagus",
    "desa": "Gudang",
    "alatTangkap": "Pukat Cincin",
    "namaKapal": "-",
    "jenisKapal": "-",
    "jenisIkan": "Ikan Selar Kuning (Selaroides leptolepis), Ikan Layang (Decapterus spp.), Ikan Lemuru (Sardinella lemuru), Ikan Bentong (Megalaspis cordyla), Ikan Banyar (Carangoides spp.), Ikan Banyar Mata Besar (Megalaspis cordyla)",
    "usahaSampingan": "",
    "tanggalValidasi": "2026-01-10",
    "validator": "MUHAMMAD S",
    "driveLink": "",
    "kodeValidasi": "VLD-V5HVJJ",
    "keterangan": ""
  },
  {
    "id": 1768027812107,
    "nama": "WAHYUDI",
    "nik": "3512120411990002",
    "whatsapp": "00000000",
    "profesi": "Nelayan Penuh Waktu",
    "status": "Anak Buah Kapal",
    "tahunLahir": "1999",
    "usia": "27",
    "kecamatan": "Asembagus",
    "desa": "Kertosari",
    "alatTangkap": "Pancing Ulur",
    "namaKapal": "-",
    "jenisKapal": "-",
    "jenisIkan": "Ikan Cakalang (Katsuwonus pelamis), Ikan Layur (Trichiurus lepturus), Ikan Marlin (Makaira spp.)",
    "usahaSampingan": "",
    "tanggalValidasi": "2026-01-10",
    "validator": "MUHAMMAD S",
    "driveLink": "",
    "kodeValidasi": "VLD-V1D8WQ",
    "keterangan": ""
  },
  {
    "id": 1768028413874,
    "nama": "RUSNADI",
    "nik": "3512111610820002",
    "whatsapp": "00000000",
    "profesi": "Nelayan Penuh Waktu",
    "status": "Anak Buah Kapal",
    "tahunLahir": "1982",
    "usia": "44",
    "kecamatan": "Arjasa",
    "desa": "Kedungdowo",
    "alatTangkap": "Pancing Ulur",
    "namaKapal": "-",
    "jenisKapal": "-",
    "jenisIkan": "Ikan Cakalang (Katsuwonus pelamis), Ikan Tuna Sirip Kuning (Thunnus albacares), Ikan Marlin (Makaira spp.)",
    "usahaSampingan": "",
    "tanggalValidasi": "2026-01-10",
    "validator": "MUHAMMAD S",
    "driveLink": "",
    "kodeValidasi": "VLD-FOOD39",
    "keterangan": ""
  },
  {
    "id": 1768028622110,
    "nama": "ASHAR RASIDI",
    "nik": "3512090101730005",
    "whatsapp": "00000000",
    "profesi": "Nelayan Penuh Waktu",
    "status": "Anak Buah Kapal",
    "tahunLahir": "1973",
    "usia": "53",
    "kecamatan": "Mangaran",
    "desa": "Trebungan",
    "alatTangkap": "Pancing Ulur",
    "namaKapal": "-",
    "jenisKapal": "-",
    "jenisIkan": "Ikan Todak (Xiphias gladius), Ikan Marlin (Makaira spp.)",
    "usahaSampingan": "",
    "tanggalValidasi": "2026-01-10",
    "validator": "MUHAMMAD S",
    "driveLink": "",
    "kodeValidasi": "VLD-TLEZTQ",
    "keterangan": ""
  },
  {
    "id": 1768184854984,
    "nama": "MISPAHOL",
    "nik": "3512171708780003",
    "whatsapp": "00000000",
    "profesi": "Nelayan Penuh Waktu",
    "status": "Anak Buah Kapal",
    "tahunLahir": "1978",
    "usia": "48",
    "kecamatan": "Bungatan",
    "desa": "Mlandingan Wetan",
    "alatTangkap": "Pancing Ulur",
    "namaKapal": "-",
    "jenisKapal": "-",
    "jenisIkan": "Ikan Sembilang (Plotosus canius), Ikan Tuna Sirip Kuning (Thunnus albacares), Ikan Todak (Xiphias gladius)",
    "usahaSampingan": "",
    "tanggalValidasi": "2026-01-11",
    "validator": "MUHAMMAD S",
    "driveLink": "",
    "kodeValidasi": "VLD-NPIZH3",
    "keterangan": ""
  },
  {
    "id": 1768184955378,
    "nama": "AJES",
    "nik": "3512170209540001",
    "whatsapp": "00000000",
    "profesi": "Nelayan Penuh Waktu",
    "status": "Anak Buah Kapal",
    "tahunLahir": "1954",
    "usia": "72",
    "kecamatan": "Bungatan",
    "desa": "Mlandingan Wetan",
    "alatTangkap": "Pukat Cincin",
    "namaKapal": "-",
    "jenisKapal": "-",
    "jenisIkan": "Ikan Tembang (Sardinella gibbosa), Ikan Kembung Lelaki & Perempuan (Rastrelliger spp.), Ikan Layang (Decapterus spp.), Ikan Teri (Stolephorus spp.)",
    "usahaSampingan": "",
    "tanggalValidasi": "2026-01-12",
    "validator": "MUHAMMAD S",
    "driveLink": "",
    "kodeValidasi": "VLD-ZKJ2HM",
    "keterangan": ""
  },
  {
    "id": 1768185134618,
    "nama": "MUSLIM",
    "nik": "3512040705830002",
    "whatsapp": "00000000",
    "profesi": "Nelayan Penuh Waktu",
    "status": "Anak Buah Kapal",
    "tahunLahir": "1983",
    "usia": "43",
    "kecamatan": "Bungatan",
    "desa": "Mlandingan Wetan",
    "alatTangkap": "Pukat Cincin",
    "namaKapal": "-",
    "jenisKapal": "-",
    "jenisIkan": "Ikan Selar Kuning (Selaroides leptolepis), Ikan Layang (Decapterus spp.), Ikan Lemuru (Sardinella lemuru)",
    "usahaSampingan": "",
    "tanggalValidasi": "2026-01-12",
    "validator": "MUHAMMAD S",
    "driveLink": "",
    "kodeValidasi": "VLD-KM6V8I",
    "keterangan": ""
  },
  {
    "id": 1768185233222,
    "nama": "DIDIK SUMOHARJO",
    "nik": "3512040910850001",
    "whatsapp": "00000000",
    "profesi": "Nelayan Penuh Waktu",
    "status": "Anak Buah Kapal",
    "tahunLahir": "1985",
    "usia": "41",
    "kecamatan": "Bungatan",
    "desa": "Mlandingan Wetan",
    "alatTangkap": "Pukat Cincin",
    "namaKapal": "-",
    "jenisKapal": "-",
    "jenisIkan": "Ikan Selar Kuning (Selaroides leptolepis), Ikan Layang (Decapterus spp.), Ikan Banyar (Carangoides spp.)",
    "usahaSampingan": "",
    "tanggalValidasi": "2026-01-12",
    "validator": "MUHAMMAD S",
    "driveLink": "",
    "kodeValidasi": "VLD-78OFWX",
    "keterangan": ""
  },
  {
    "id": 1768185361503,
    "nama": "DARTO",
    "nik": "3512171910560001",
    "whatsapp": "00000000",
    "profesi": "Nelayan Penuh Waktu",
    "status": "Anak Buah Kapal",
    "tahunLahir": "1956",
    "usia": "70",
    "kecamatan": "Bungatan",
    "desa": "Bungatan",
    "alatTangkap": "Pukat Cincin",
    "namaKapal": "-",
    "jenisKapal": "-",
    "jenisIkan": "Ikan Lemuru (Sardinella lemuru), Ikan Banyar (Carangoides spp.), Ikan Banyar Mata Besar (Megalaspis cordyla)",
    "usahaSampingan": "",
    "tanggalValidasi": "2026-01-12",
    "validator": "MUHAMMAD S",
    "driveLink": "",
    "kodeValidasi": "VLD-EVPZ8H",
    "keterangan": ""
  },
  {
    "id": 1768185493549,
    "nama": "NUR HASAN",
    "nik": "3512170102790004",
    "whatsapp": "00000000",
    "profesi": "Nelayan Penuh Waktu",
    "status": "Anak Buah Kapal",
    "tahunLahir": "1979",
    "usia": "47",
    "kecamatan": "Bungatan",
    "desa": "Mlandingan Wetan",
    "alatTangkap": "Pukat Cincin",
    "namaKapal": "-",
    "jenisKapal": "-",
    "jenisIkan": "Ikan Tongkol (Euthynnus affinis), Ikan Cakalang (Katsuwonus pelamis), Ikan Tuna Sirip Kuning (Thunnus albacares)",
    "usahaSampingan": "",
    "tanggalValidasi": "2026-01-12",
    "validator": "MUHAMMAD S",
    "driveLink": "",
    "kodeValidasi": "VLD-72Z4L5",
    "keterangan": ""
  },
  {
    "id": 1768185576153,
    "nama": "SUBKI",
    "nik": "3512170107660076",
    "whatsapp": "00000000",
    "profesi": "Nelayan Penuh Waktu",
    "status": "Anak Buah Kapal",
    "tahunLahir": "1966",
    "usia": "60",
    "kecamatan": "Bungatan",
    "desa": "Mlandingan Wetan",
    "alatTangkap": "Pukat Cincin",
    "namaKapal": "-",
    "jenisKapal": "-",
    "jenisIkan": "Ikan Tongkol (Euthynnus affinis), Ikan Cakalang (Katsuwonus pelamis), Ikan Tuna Sirip Kuning (Thunnus albacares)",
    "usahaSampingan": "",
    "tanggalValidasi": "2026-01-12",
    "validator": "MUHAMMAD S",
    "driveLink": "",
    "kodeValidasi": "VLD-CIPTTT",
    "keterangan": ""
  }
];
