// DATA NELAYAN GLOBAL - SISTEM PEMETAAN NELAYAN
// File: sumberejo.js
// Dibuat: 27/1/2026, 10.10.19
// Jumlah Data: 32

window.SIMATA_BACKUP_DATA = [
  {
    "id": 1768024012170,
    "nama": "M. HOSEN MAKKI",
    "nik": "3512020603660001",
    "whatsapp": "082214641188",
    "profesi": "Nelayan Penuh Waktu",
    "status": "Anak Buah Kapal",
    "tahunLahir": "1966",
    "usia": "60",
    "kecamatan": "Besuki",
    "desa": "Blimbing",
    "alatTangkap": "Pancing Ulur",
    "namaKapal": "-",
    "jenisKapal": "-",
    "jenisIkan": "Ikan Marlin (Makaira spp.), Ikan Cucut (Carcharhinus limbatus)",
    "usahaSampingan": "",
    "tanggalValidasi": "2026-01-10",
    "validator": "MUHAMMAD S",
    "driveLink": "",
    "kodeValidasi": "VLD-1X39V8",
    "keterangan": ""
  },
  {
    "id": 1768024193373,
    "nama": "MOH. MISBAH",
    "nik": "3512021309830005",
    "whatsapp": "00000000",
    "profesi": "Nelayan Penuh Waktu",
    "status": "Anak Buah Kapal",
    "tahunLahir": "1983",
    "usia": "43",
    "kecamatan": "Besuki",
    "desa": "Bloro",
    "alatTangkap": "Pukat Cincin",
    "namaKapal": "-",
    "jenisKapal": "-",
    "jenisIkan": "Ikan Selar Kuning (Selaroides leptolepis), Ikan Layang (Decapterus spp.), Ikan Banyar (Carangoides spp.)",
    "usahaSampingan": "",
    "tanggalValidasi": "2026-01-10",
    "validator": "MUHAMMAD S",
    "driveLink": "",
    "kodeValidasi": "VLD-CL7Y77",
    "keterangan": ""
  },
  {
    "id": 1768024420072,
    "nama": "SUPATNO",
    "nik": "3512020304780005",
    "whatsapp": "00000000",
    "profesi": "Nelayan Penuh Waktu",
    "status": "Anak Buah Kapal",
    "tahunLahir": "1978",
    "usia": "48",
    "kecamatan": "Besuki",
    "desa": "Jetis",
    "alatTangkap": "Pancing",
    "namaKapal": "-",
    "jenisKapal": "-",
    "jenisIkan": "Ikan Tembang (Sardinella gibbosa), Ikan Japuh (Caranx spp.), Ikan Banyar Mata Besar (Megalaspis cordyla)",
    "usahaSampingan": "",
    "tanggalValidasi": "2026-01-10",
    "validator": "MUHAMMAD S",
    "driveLink": "",
    "kodeValidasi": "VLD-91U5I2",
    "keterangan": ""
  },
  {
    "id": 1768024524874,
    "nama": "MUTHAR",
    "nik": "3512020104810004",
    "whatsapp": "00000000",
    "profesi": "Nelayan Penuh Waktu",
    "status": "Anak Buah Kapal",
    "tahunLahir": "1981",
    "usia": "45",
    "kecamatan": "Besuki",
    "desa": "Jetis",
    "alatTangkap": "Pukat Cincin",
    "namaKapal": "-",
    "jenisKapal": "-",
    "jenisIkan": "Ikan Japuh (Caranx spp.), Ikan Lemuru (Sardinella lemuru), Ikan Banyar (Carangoides spp.), Ikan Banyar Mata Besar (Megalaspis cordyla)",
    "usahaSampingan": "",
    "tanggalValidasi": "2026-01-10",
    "validator": "MUHAMMAD S",
    "driveLink": "",
    "kodeValidasi": "VLD-VCR738",
    "keterangan": ""
  },
  {
    "id": 1768024693008,
    "nama": "HASAN BASRI",
    "nik": "3512022206820004",
    "whatsapp": "00000000",
    "profesi": "Nelayan Penuh Waktu",
    "status": "Anak Buah Kapal",
    "tahunLahir": "1982",
    "usia": "44",
    "kecamatan": "Besuki",
    "desa": "Kalimas",
    "alatTangkap": "Pukat Cincin",
    "namaKapal": "-",
    "jenisKapal": "-",
    "jenisIkan": "Ikan Cucut (Carcharhinus limbatus), Ikan Selar Kuning (Selaroides leptolepis), Ikan Layang (Decapterus spp.), Ikan Japuh (Caranx spp.), Ikan Lemuru (Sardinella lemuru), Ikan Banyar (Carangoides spp.)",
    "usahaSampingan": "",
    "tanggalValidasi": "2026-01-10",
    "validator": "MUHAMMAD S",
    "driveLink": "",
    "kodeValidasi": "VLD-3WEC4L",
    "keterangan": ""
  },
  {
    "id": 1768027674319,
    "nama": "AMRI WALIYADI",
    "nik": "3512132707870002",
    "whatsapp": "00000000",
    "profesi": "Nelayan Penuh Waktu",
    "status": "Anak Buah Kapal",
    "tahunLahir": "1987",
    "usia": "39",
    "kecamatan": "Asembagus",
    "desa": "Gudang",
    "alatTangkap": "Pukat Cincin",
    "namaKapal": "-",
    "jenisKapal": "-",
    "jenisIkan": "Ikan Selar Kuning (Selaroides leptolepis), Ikan Layang (Decapterus spp.), Ikan Lemuru (Sardinella lemuru), Ikan Bentong (Megalaspis cordyla), Ikan Banyar (Carangoides spp.), Ikan Banyar Mata Besar (Megalaspis cordyla)",
    "usahaSampingan": "",
    "tanggalValidasi": "2026-01-10",
    "validator": "MUHAMMAD S",
    "driveLink": "",
    "kodeValidasi": "VLD-V5HVJJ",
    "keterangan": ""
  },
  {
    "id": 1768027812107,
    "nama": "WAHYUDI",
    "nik": "3512120411990002",
    "whatsapp": "00000000",
    "profesi": "Nelayan Penuh Waktu",
    "status": "Anak Buah Kapal",
    "tahunLahir": "1999",
    "usia": "27",
    "kecamatan": "Asembagus",
    "desa": "Kertosari",
    "alatTangkap": "Pancing Ulur",
    "namaKapal": "-",
    "jenisKapal": "-",
    "jenisIkan": "Ikan Cakalang (Katsuwonus pelamis), Ikan Layur (Trichiurus lepturus), Ikan Marlin (Makaira spp.)",
    "usahaSampingan": "",
    "tanggalValidasi": "2026-01-10",
    "validator": "MUHAMMAD S",
    "driveLink": "",
    "kodeValidasi": "VLD-V1D8WQ",
    "keterangan": ""
  },
  {
    "id": 1768028413874,
    "nama": "RUSNADI",
    "nik": "3512111610820002",
    "whatsapp": "00000000",
    "profesi": "Nelayan Penuh Waktu",
    "status": "Anak Buah Kapal",
    "tahunLahir": "1982",
    "usia": "44",
    "kecamatan": "Arjasa",
    "desa": "Kedungdowo",
    "alatTangkap": "Pancing Ulur",
    "namaKapal": "-",
    "jenisKapal": "-",
    "jenisIkan": "Ikan Cakalang (Katsuwonus pelamis), Ikan Tuna Sirip Kuning (Thunnus albacares), Ikan Marlin (Makaira spp.)",
    "usahaSampingan": "",
    "tanggalValidasi": "2026-01-10",
    "validator": "MUHAMMAD S",
    "driveLink": "",
    "kodeValidasi": "VLD-FOOD39",
    "keterangan": ""
  },
  {
    "id": 1768028622110,
    "nama": "ASHAR RASIDI",
    "nik": "3512090101730005",
    "whatsapp": "00000000",
    "profesi": "Nelayan Penuh Waktu",
    "status": "Anak Buah Kapal",
    "tahunLahir": "1973",
    "usia": "53",
    "kecamatan": "Mangaran",
    "desa": "Trebungan",
    "alatTangkap": "Pancing Ulur",
    "namaKapal": "-",
    "jenisKapal": "-",
    "jenisIkan": "Ikan Todak (Xiphias gladius), Ikan Marlin (Makaira spp.)",
    "usahaSampingan": "",
    "tanggalValidasi": "2026-01-10",
    "validator": "MUHAMMAD S",
    "driveLink": "",
    "kodeValidasi": "VLD-TLEZTQ",
    "keterangan": ""
  },
  {
    "id": 1768184854984,
    "nama": "MISPAHOL",
    "nik": "3512171708780003",
    "whatsapp": "00000000",
    "profesi": "Nelayan Penuh Waktu",
    "status": "Anak Buah Kapal",
    "tahunLahir": "1978",
    "usia": "48",
    "kecamatan": "Bungatan",
    "desa": "Mlandingan Wetan",
    "alatTangkap": "Pancing Ulur",
    "namaKapal": "-",
    "jenisKapal": "-",
    "jenisIkan": "Ikan Sembilang (Plotosus canius), Ikan Tuna Sirip Kuning (Thunnus albacares), Ikan Todak (Xiphias gladius)",
    "usahaSampingan": "",
    "tanggalValidasi": "2026-01-11",
    "validator": "MUHAMMAD S",
    "driveLink": "",
    "kodeValidasi": "VLD-NPIZH3",
    "keterangan": ""
  },
  {
    "id": 1768184955378,
    "nama": "AJES",
    "nik": "3512170209540001",
    "whatsapp": "00000000",
    "profesi": "Nelayan Penuh Waktu",
    "status": "Anak Buah Kapal",
    "tahunLahir": "1954",
    "usia": "72",
    "kecamatan": "Bungatan",
    "desa": "Mlandingan Wetan",
    "alatTangkap": "Pukat Cincin",
    "namaKapal": "-",
    "jenisKapal": "-",
    "jenisIkan": "Ikan Tembang (Sardinella gibbosa), Ikan Kembung Lelaki & Perempuan (Rastrelliger spp.), Ikan Layang (Decapterus spp.), Ikan Teri (Stolephorus spp.)",
    "usahaSampingan": "",
    "tanggalValidasi": "2026-01-12",
    "validator": "MUHAMMAD S",
    "driveLink": "",
    "kodeValidasi": "VLD-ZKJ2HM",
    "keterangan": ""
  },
  {
    "id": 1768185134618,
    "nama": "MUSLIM",
    "nik": "3512040705830002",
    "whatsapp": "00000000",
    "profesi": "Nelayan Penuh Waktu",
    "status": "Anak Buah Kapal",
    "tahunLahir": "1983",
    "usia": "43",
    "kecamatan": "Bungatan",
    "desa": "Mlandingan Wetan",
    "alatTangkap": "Pukat Cincin",
    "namaKapal": "-",
    "jenisKapal": "-",
    "jenisIkan": "Ikan Selar Kuning (Selaroides leptolepis), Ikan Layang (Decapterus spp.), Ikan Lemuru (Sardinella lemuru)",
    "usahaSampingan": "",
    "tanggalValidasi": "2026-01-12",
    "validator": "MUHAMMAD S",
    "driveLink": "",
    "kodeValidasi": "VLD-KM6V8I",
    "keterangan": ""
  },
  {
    "id": 1768185233222,
    "nama": "DIDIK SUMOHARJO",
    "nik": "3512040910850001",
    "whatsapp": "00000000",
    "profesi": "Nelayan Penuh Waktu",
    "status": "Anak Buah Kapal",
    "tahunLahir": "1985",
    "usia": "41",
    "kecamatan": "Bungatan",
    "desa": "Mlandingan Wetan",
    "alatTangkap": "Pukat Cincin",
    "namaKapal": "-",
    "jenisKapal": "-",
    "jenisIkan": "Ikan Selar Kuning (Selaroides leptolepis), Ikan Layang (Decapterus spp.), Ikan Banyar (Carangoides spp.)",
    "usahaSampingan": "",
    "tanggalValidasi": "2026-01-12",
    "validator": "MUHAMMAD S",
    "driveLink": "",
    "kodeValidasi": "VLD-78OFWX",
    "keterangan": ""
  },
  {
    "id": "1768185361503",
    "nama": "DARTO",
    "nik": "3512171910560001",
    "whatsapp": "00000000",
    "profesi": "Nelayan Penuh Waktu",
    "status": "Anak Buah Kapal",
    "tahunLahir": "1956",
    "usia": "70",
    "kecamatan": "Bungatan",
    "desa": "Mlandingan Wetan",
    "alatTangkap": "Pukat Cincin",
    "namaKapal": "-",
    "jenisKapal": "-",
    "jenisIkan": "Ikan Lemuru (Sardinella lemuru), Ikan Banyar (Carangoides spp.), Ikan Banyar Mata Besar (Megalaspis cordyla)",
    "usahaSampingan": "",
    "tanggalValidasi": "2026-01-12",
    "validator": "MUHAMMAD S",
    "driveLink": "",
    "kodeValidasi": "VLD-EVPZ8H",
    "keterangan": ""
  },
  {
    "id": 1768185493549,
    "nama": "NUR HASAN",
    "nik": "3512170102790004",
    "whatsapp": "00000000",
    "profesi": "Nelayan Penuh Waktu",
    "status": "Anak Buah Kapal",
    "tahunLahir": "1979",
    "usia": "47",
    "kecamatan": "Bungatan",
    "desa": "Mlandingan Wetan",
    "alatTangkap": "Pukat Cincin",
    "namaKapal": "-",
    "jenisKapal": "-",
    "jenisIkan": "Ikan Tongkol (Euthynnus affinis), Ikan Cakalang (Katsuwonus pelamis), Ikan Tuna Sirip Kuning (Thunnus albacares)",
    "usahaSampingan": "",
    "tanggalValidasi": "2026-01-12",
    "validator": "MUHAMMAD S",
    "driveLink": "",
    "kodeValidasi": "VLD-72Z4L5",
    "keterangan": ""
  },
  {
    "id": 1768185576153,
    "nama": "SUBKI",
    "nik": "3512170107660076",
    "whatsapp": "00000000",
    "profesi": "Nelayan Penuh Waktu",
    "status": "Anak Buah Kapal",
    "tahunLahir": "1966",
    "usia": "60",
    "kecamatan": "Bungatan",
    "desa": "Mlandingan Wetan",
    "alatTangkap": "Pukat Cincin",
    "namaKapal": "-",
    "jenisKapal": "-",
    "jenisIkan": "Ikan Tongkol (Euthynnus affinis), Ikan Cakalang (Katsuwonus pelamis), Ikan Tuna Sirip Kuning (Thunnus albacares)",
    "usahaSampingan": "",
    "tanggalValidasi": "2026-01-12",
    "validator": "MUHAMMAD S",
    "driveLink": "",
    "kodeValidasi": "VLD-CIPTTT",
    "keterangan": ""
  },
  {
    "id": 1768187044020,
    "nama": "BUYONO",
    "nik": "3512100107880116",
    "whatsapp": "00000000",
    "profesi": "Nelayan Penuh Waktu",
    "status": "Anak Buah Kapal",
    "tahunLahir": "1988",
    "usia": "38",
    "kecamatan": "Kapongan",
    "desa": "Gebangan",
    "alatTangkap": "Pukat Cincin",
    "namaKapal": "-",
    "jenisKapal": "-",
    "jenisIkan": "Ikan Tongkol (Euthynnus affinis), Ikan Cakalang (Katsuwonus pelamis), Ikan Tenggiri (Scomberomorus commerson)",
    "usahaSampingan": "",
    "tanggalValidasi": "2026-01-12",
    "validator": "MUHAMMAD S",
    "driveLink": "",
    "kodeValidasi": "VLD-Z233HL",
    "keterangan": ""
  },
  {
    "id": 1768187172247,
    "nama": "YONDRO ALIWONGSO",
    "nik": "3512101409700001",
    "whatsapp": "00000000",
    "profesi": "Nelayan Penuh Waktu",
    "status": "Anak Buah Kapal",
    "tahunLahir": "1970",
    "usia": "56",
    "kecamatan": "Kapongan",
    "desa": "Gebangan",
    "alatTangkap": "Pukat Cincin",
    "namaKapal": "-",
    "jenisKapal": "-",
    "jenisIkan": "Ikan Tongkol (Euthynnus affinis), Ikan Cakalang (Katsuwonus pelamis), Ikan Tenggiri (Scomberomorus commerson)",
    "usahaSampingan": "",
    "tanggalValidasi": "2026-01-12",
    "validator": "MUHAMMAD S",
    "driveLink": "",
    "kodeValidasi": "VLD-ZBO971",
    "keterangan": ""
  },
  {
    "id": 1768187291057,
    "nama": "PARDI",
    "nik": "3512100608740001",
    "whatsapp": "00000000",
    "profesi": "Nelayan Penuh Waktu",
    "status": "Anak Buah Kapal",
    "tahunLahir": "1974",
    "usia": "52",
    "kecamatan": "Kapongan",
    "desa": "Gebangan",
    "alatTangkap": "Pukat Cincin",
    "namaKapal": "-",
    "jenisKapal": "-",
    "jenisIkan": "Ikan Tongkol (Euthynnus affinis), Ikan Tenggiri (Scomberomorus commerson), Ikan Tuna Sirip Kuning (Thunnus albacares)",
    "usahaSampingan": "",
    "tanggalValidasi": "2026-01-12",
    "validator": "MUHAMMAD S",
    "driveLink": "",
    "kodeValidasi": "VLD-2YLAFC",
    "keterangan": ""
  },
  {
    "id": 1768188568534,
    "nama": "MOHAMMAD FENDI",
    "nik": "3512050712890001",
    "whatsapp": "00000000",
    "profesi": "Nelayan Penuh Waktu",
    "status": "Anak Buah Kapal",
    "tahunLahir": "1989",
    "usia": "37",
    "kecamatan": "Kendit",
    "desa": "Kendit",
    "alatTangkap": "Pancing",
    "namaKapal": "-",
    "jenisKapal": "-",
    "jenisIkan": "Ikan Banyar (Carangoides spp.), Ikan Marlin (Makaira spp.)",
    "usahaSampingan": "",
    "tanggalValidasi": "2026-01-12",
    "validator": "MUHAMMAD S",
    "driveLink": "",
    "kodeValidasi": "VLD-XIUXAT",
    "keterangan": ""
  },
  {
    "id": 1768188755577,
    "nama": "MUHAMMAD FADILAH",
    "nik": "3512050510950001",
    "whatsapp": "00000000",
    "profesi": "Nelayan Penuh Waktu",
    "status": "Anak Buah Kapal",
    "tahunLahir": "1995",
    "usia": "31",
    "kecamatan": "Kendit",
    "desa": "Kendit",
    "alatTangkap": "Pancing",
    "namaKapal": "-",
    "jenisKapal": "-",
    "jenisIkan": "Ikan Banyar (Carangoides spp.), Ikan Banyar Mata Besar (Megalaspis cordyla), Ikan Tenggiri (Scomberomorus commerson)",
    "usahaSampingan": "",
    "tanggalValidasi": "2026-01-12",
    "validator": "MUHAMMAD S",
    "driveLink": "",
    "kodeValidasi": "VLD-77VS18",
    "keterangan": ""
  },
  {
    "id": 1768188870063,
    "nama": "ADYTYA AINUR RIFQI",
    "nik": "3512081006970001",
    "whatsapp": "00000000",
    "profesi": "Nelayan Penuh Waktu",
    "status": "Anak Buah Kapal",
    "tahunLahir": "1997",
    "usia": "29",
    "kecamatan": "Kendit",
    "desa": "Kendit",
    "alatTangkap": "Pukat Cincin",
    "namaKapal": "-",
    "jenisKapal": "-",
    "jenisIkan": "Ikan Selar Kuning (Selaroides leptolepis), Ikan Lemuru (Sardinella lemuru), Ikan Bentong (Megalaspis cordyla), Ikan Banyar (Carangoides spp.)",
    "usahaSampingan": "",
    "tanggalValidasi": "2026-01-12",
    "validator": "MUHAMMAD S",
    "driveLink": "",
    "kodeValidasi": "VLD-3UWWT5",
    "keterangan": ""
  },
  {
    "id": 1768189043987,
    "nama": "ACHMAD BUSAIRI",
    "nik": "3512050606950001",
    "whatsapp": "00000000",
    "profesi": "Nelayan Penuh Waktu",
    "status": "Anak Buah Kapal",
    "tahunLahir": "1995",
    "usia": "31",
    "kecamatan": "Kendit",
    "desa": "Kendit",
    "alatTangkap": "Pancing",
    "namaKapal": "-",
    "jenisKapal": "-",
    "jenisIkan": "Ikan Mangla (Pomadasys spp.), Ikan Sebelah (Pleuronectiformes), Ikan Kerapu (Epinephelus spp.)",
    "usahaSampingan": "",
    "tanggalValidasi": "2026-01-12",
    "validator": "MUHAMMAD S",
    "driveLink": "",
    "kodeValidasi": "VLD-ZYA7NQ",
    "keterangan": ""
  },
  {
    "id": 1768189266800,
    "nama": "ABD RAZAK",
    "nik": "3512052707620001",
    "whatsapp": "00000000",
    "profesi": "Nelayan Penuh Waktu",
    "status": "Anak Buah Kapal",
    "tahunLahir": "1962",
    "usia": "64",
    "kecamatan": "Kendit",
    "desa": "Kendit",
    "alatTangkap": "Pancing",
    "namaKapal": "-",
    "jenisKapal": "-",
    "jenisIkan": "Ikan Petek (Leiognathus spp.), Ikan Layang (Decapterus spp.), Ikan Tenggiri (Scomberomorus commerson)",
    "usahaSampingan": "",
    "tanggalValidasi": "2026-01-12",
    "validator": "MUHAMMAD S",
    "driveLink": "",
    "kodeValidasi": "VLD-0CD4GC",
    "keterangan": ""
  },
  {
    "id": 1768189400197,
    "nama": "ABD RAHEM",
    "nik": "3512050107750092",
    "whatsapp": "00000000",
    "profesi": "Nelayan Penuh Waktu",
    "status": "Anak Buah Kapal",
    "tahunLahir": "1975",
    "usia": "51",
    "kecamatan": "Kendit",
    "desa": "Kendit",
    "alatTangkap": "Pukat Cincin",
    "namaKapal": "-",
    "jenisKapal": "-",
    "jenisIkan": "Ikan Selar Kuning (Selaroides leptolepis), Ikan Lemuru (Sardinella lemuru), Ikan Banyar (Carangoides spp.)",
    "usahaSampingan": "",
    "tanggalValidasi": "2026-01-12",
    "validator": "MUHAMMAD S",
    "driveLink": "",
    "kodeValidasi": "VLD-L6YKXA",
    "keterangan": ""
  },
  {
    "id": 1768189483238,
    "nama": "MOHAMMAD SULAIMAN",
    "nik": "3512050712820002",
    "whatsapp": "00000000",
    "profesi": "Nelayan Penuh Waktu",
    "status": "Anak Buah Kapal",
    "tahunLahir": "1982",
    "usia": "44",
    "kecamatan": "Kendit",
    "desa": "Kendit",
    "alatTangkap": "Pukat Cincin",
    "namaKapal": "-",
    "jenisKapal": "-",
    "jenisIkan": "Ikan Tuna Sirip Kuning (Thunnus albacares), Ikan Tuna Mata Besar (Thunnus obesus), Ikan Layur (Trichiurus lepturus), Ikan Todak (Xiphias gladius)",
    "usahaSampingan": "",
    "tanggalValidasi": "2026-01-12",
    "validator": "MUHAMMAD S",
    "driveLink": "",
    "kodeValidasi": "VLD-9IZIPY",
    "keterangan": ""
  },
  {
    "id": 1768193090570,
    "nama": "MOH EDIYANTO",
    "nik": "3512081405900007",
    "whatsapp": "00000000",
    "profesi": "Nelayan Penuh Waktu",
    "status": "Anak Buah Kapal",
    "tahunLahir": "1990",
    "usia": "36",
    "kecamatan": "Jangkar",
    "desa": "Pesanggrahan",
    "alatTangkap": "Pancing Ulur",
    "namaKapal": "-",
    "jenisKapal": "-",
    "jenisIkan": "Ikan Layur (Trichiurus lepturus), Ikan Todak (Xiphias gladius), Ikan Marlin (Makaira spp.)",
    "usahaSampingan": "",
    "tanggalValidasi": "2026-01-12",
    "validator": "MUHAMMAD S",
    "driveLink": "",
    "kodeValidasi": "VLD-WC4GGY",
    "keterangan": ""
  },
  {
    "id": 1768193215061,
    "nama": "ADI HARTONO",
    "nik": "3512121007880001",
    "whatsapp": "00000000",
    "profesi": "Nelayan Penuh Waktu",
    "status": "Anak Buah Kapal",
    "tahunLahir": "1988",
    "usia": "38",
    "kecamatan": "Jangkar",
    "desa": "Pesanggrahan",
    "alatTangkap": "Pancing Ulur",
    "namaKapal": "-",
    "jenisKapal": "-",
    "jenisIkan": "Ikan Togek / Mendut (Star Triggerfish), Ikan Tuna Mata Besar (Thunnus obesus), Ikan Todak (Xiphias gladius)",
    "usahaSampingan": "",
    "tanggalValidasi": "2026-01-12",
    "validator": "MUHAMMAD S",
    "driveLink": "",
    "kodeValidasi": "VLD-A5R7TL",
    "keterangan": ""
  },
  {
    "id": 1768193450597,
    "nama": "MOH AMIRUL MU'MININ",
    "nik": "3512122706960001",
    "whatsapp": "00000000",
    "profesi": "Nelayan Penuh Waktu",
    "status": "Anak Buah Kapal",
    "tahunLahir": "1996",
    "usia": "30",
    "kecamatan": "Jangkar",
    "desa": "Palangan",
    "alatTangkap": "Pukat Cincin",
    "namaKapal": "-",
    "jenisKapal": "-",
    "jenisIkan": "Ikan Tembang (Sardinella gibbosa), Ikan Selar Kuning (Selaroides leptolepis), Ikan Layang (Decapterus spp.), Ikan Banyar (Carangoides spp.)",
    "usahaSampingan": "",
    "tanggalValidasi": "2026-01-12",
    "validator": "MUHAMMAD S",
    "driveLink": "",
    "kodeValidasi": "VLD-D9O5M5",
    "keterangan": ""
  },
  {
    "id": 1768193581203,
    "nama": "SYAIFUL BAHRI",
    "nik": "3512120211820002",
    "whatsapp": "00000000",
    "profesi": "Nelayan Penuh Waktu",
    "status": "Anak Buah Kapal",
    "tahunLahir": "1982",
    "usia": "44",
    "kecamatan": "Jangkar",
    "desa": "Palangan",
    "alatTangkap": "Pancing Ulur",
    "namaKapal": "-",
    "jenisKapal": "-",
    "jenisIkan": "Ikan Layur (Trichiurus lepturus), Ikan Todak (Xiphias gladius), Ikan Marlin (Makaira spp.)",
    "usahaSampingan": "",
    "tanggalValidasi": "2026-01-12",
    "validator": "MUHAMMAD S",
    "driveLink": "",
    "kodeValidasi": "VLD-J5AOVZ",
    "keterangan": ""
  },
  {
    "id": 1768193722685,
    "nama": "RAHMAN",
    "nik": "3512121603860001",
    "whatsapp": "00000000",
    "profesi": "Nelayan Penuh Waktu",
    "status": "Anak Buah Kapal",
    "tahunLahir": "1986",
    "usia": "40",
    "kecamatan": "Jangkar",
    "desa": "Palangan",
    "alatTangkap": "Pukat Cincin",
    "namaKapal": "-",
    "jenisKapal": "-",
    "jenisIkan": "Ikan Layur (Trichiurus lepturus), Ikan Selar Kuning (Selaroides leptolepis), Ikan Lemuru (Sardinella lemuru), Ikan Banyar (Carangoides spp.)",
    "usahaSampingan": "",
    "tanggalValidasi": "2026-01-12",
    "validator": "MUHAMMAD S",
    "driveLink": "",
    "kodeValidasi": "VLD-QC2TBG",
    "keterangan": ""
  },
  {
    "id": 1768193796149,
    "nama": "SUGIANTO",
    "nik": "3512120105730003",
    "whatsapp": "00000000",
    "profesi": "Nelayan Penuh Waktu",
    "status": "Anak Buah Kapal",
    "tahunLahir": "1973",
    "usia": "53",
    "kecamatan": "Jangkar",
    "desa": "Palangan",
    "alatTangkap": "Pukat Cincin",
    "namaKapal": "-",
    "jenisKapal": "-",
    "jenisIkan": "Ikan Tongkol (Euthynnus affinis), Ikan Cakalang (Katsuwonus pelamis), Ikan Tenggiri (Scomberomorus commerson), Ikan Tuna Sirip Kuning (Thunnus albacares), Ikan Layur (Trichiurus lepturus)",
    "usahaSampingan": "",
    "tanggalValidasi": "2026-01-12",
    "validator": "MUHAMMAD S",
    "driveLink": "",
    "kodeValidasi": "VLD-CL0ZAA",
    "keterangan": ""
  }
];
